-- =============================================================================
--  schema.sql  —  Digital Sari-Sari Store: Inventory, Sales & "Utang" Database
-- =============================================================================
--  Target  : PostgreSQL 13+
--  Design   : Third Normal Form (3NF). No repeating groups, no partial
--             dependencies, no transitive dependencies.
--  Money    : NUMERIC(10,2) — Philippine Peso (₱). Never use floating point
--             for cash.
--  Keys     : Surrogate integer identity PKs. Declared GENERATED BY DEFAULT
--             (not ALWAYS) so legacy ledger rows can be imported with their
--             original numbering during the paper -> digital migration.
--  Run with : psql -v ON_ERROR_STOP=1 -f schema.sql
--
--  The whole script is wrapped in a single transaction: it either builds the
--  entire database cleanly or rolls back, leaving nothing half-created.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- 0. Clean slate (idempotent re-runs during development)
-- -----------------------------------------------------------------------------
DROP VIEW  IF EXISTS v_utang_ledger      CASCADE;
DROP VIEW  IF EXISTS v_customer_balances CASCADE;
DROP VIEW  IF EXISTS v_product_stock     CASCADE;

DROP TABLE IF EXISTS credit_payments     CASCADE;
DROP TABLE IF EXISTS transaction_items   CASCADE;
DROP TABLE IF EXISTS transactions        CASCADE;
DROP TABLE IF EXISTS restock_items       CASCADE;
DROP TABLE IF EXISTS restocks            CASCADE;
DROP TABLE IF EXISTS products            CASCADE;
DROP TABLE IF EXISTS customers           CASCADE;
DROP TABLE IF EXISTS suppliers           CASCADE;
DROP TABLE IF EXISTS units               CASCADE;
DROP TABLE IF EXISTS categories          CASCADE;

DROP FUNCTION IF EXISTS set_updated_at()        CASCADE;
DROP FUNCTION IF EXISTS apply_stock_on_sale()   CASCADE;
DROP FUNCTION IF EXISTS apply_stock_on_restock() CASCADE;


-- -----------------------------------------------------------------------------
-- 1. Shared trigger function: keep updated_at honest on mutable master tables
-- -----------------------------------------------------------------------------
CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- =============================================================================
-- 2. LOOKUP TABLES
-- =============================================================================

-- Product categories (Beverages, Snacks, Canned Goods, ...).
CREATE TABLE categories (
    category_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL UNIQUE,
    description  TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE categories IS 'Product categories. Removes the repeating category text from products (3NF).';

-- Units of measure. Sari-sari stores sell "tingi" (per piece/stick/sachet),
-- so the unit is an attribute of HOW a product is sold.
CREATE TABLE units (
    unit_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       TEXT NOT NULL UNIQUE,          -- pc, sachet, bottle, can, pack, kg, stick
    name       TEXT NOT NULL,                 -- human readable
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE units IS 'Units of measure / selling unit (tingi vs. whole).';


-- =============================================================================
-- 3. MASTER TABLES
-- =============================================================================

-- Suppliers / wholesalers the owner buys stock from.
CREATE TABLE suppliers (
    supplier_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           TEXT NOT NULL,
    contact_person TEXT,
    phone          TEXT,
    address        TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE suppliers IS 'Where inbound stock comes from. Referenced by restocks.';

-- The catalog. current_price is today's selling price; historical selling
-- prices are snapshotted per sale in transaction_items.unit_price.
CREATE TABLE products (
    product_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id    INT NOT NULL REFERENCES categories(category_id) ON DELETE RESTRICT,
    unit_id        INT NOT NULL REFERENCES units(unit_id)          ON DELETE RESTRICT,
    name           TEXT NOT NULL,
    description    TEXT,
    barcode        TEXT UNIQUE,                          -- nullable; not every tingi item is scanned
    current_price  NUMERIC(10,2) NOT NULL CHECK (current_price >= 0),
    reorder_level  INT NOT NULL DEFAULT 0  CHECK (reorder_level >= 0),
    stock_on_hand  INT NOT NULL DEFAULT 0,               -- maintained by triggers (see §7)
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,        -- soft-delete; never lose history
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON COLUMN products.current_price IS 'Today''s selling price. Past prices live in transaction_items.unit_price.';
COMMENT ON COLUMN products.stock_on_hand IS 'Trigger-maintained running stock. Reconcile against v_product_stock.on_hand.';

-- Credit ("utang") customers. Walk-in cash buyers are NOT stored here;
-- their sales simply carry a NULL customer_id.
CREATE TABLE customers (
    customer_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     TEXT NOT NULL,
    nickname      TEXT,                                  -- "palayaw" — how the owner actually files them
    phone         TEXT,
    address       TEXT,
    credit_limit  NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (credit_limit >= 0),
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE customers IS 'Named credit customers. Cash walk-ins are NULL customer_id on the sale.';


-- =============================================================================
-- 4. INBOUND STOCK (RESTOCKS)  — header / line split
-- =============================================================================

-- One row per delivery / buying trip (the header).
CREATE TABLE restocks (
    restock_id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id   INT NOT NULL REFERENCES suppliers(supplier_id) ON DELETE RESTRICT,
    restock_date  TIMESTAMPTZ NOT NULL DEFAULT now(),
    reference_no  TEXT,                                  -- supplier invoice / DR number
    notes         TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE restocks IS 'Inbound stock event header (one delivery / buying trip).';

-- The repeating group: many products per restock (the lines).
-- unit_cost is snapshotted here — purchase cost changes over time and must
-- not be lost when the catalog price moves.
CREATE TABLE restock_items (
    restock_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restock_id      INT NOT NULL REFERENCES restocks(restock_id) ON DELETE CASCADE,
    product_id      INT NOT NULL REFERENCES products(product_id) ON DELETE RESTRICT,
    quantity        INT NOT NULL CHECK (quantity > 0),
    unit_cost       NUMERIC(10,2) NOT NULL CHECK (unit_cost >= 0)
    -- line subtotal (quantity * unit_cost) is DERIVED, never stored (3NF).
);
COMMENT ON TABLE restock_items IS 'Restock line items. Resolves products<->restocks many-to-many.';


-- =============================================================================
-- 5. SALES  — header / line split
-- =============================================================================

-- One row per point-of-sale transaction (the header).
-- payment_type drives the "utang" logic: 'credit' sales become charges against
-- the customer's running balance (see v_customer_balances / v_utang_ledger).
CREATE TABLE transactions (
    transaction_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      INT REFERENCES customers(customer_id) ON DELETE RESTRICT,  -- NULL = cash walk-in
    transaction_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    payment_type     TEXT NOT NULL DEFAULT 'cash'
                       CHECK (payment_type IN ('cash', 'credit')),
    notes            TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- A credit sale MUST be tied to a named customer; cash sales may be anonymous.
    CONSTRAINT credit_requires_customer
        CHECK (payment_type <> 'credit' OR customer_id IS NOT NULL)
);
COMMENT ON TABLE transactions IS 'Sale header. payment_type=''credit'' is an utang charge against the customer.';

-- The repeating group: many products per sale (the lines).
-- unit_price is the selling price AT THE MOMENT OF SALE — a snapshot so that a
-- decade of receipts stays correct even after the catalog price changes.
CREATE TABLE transaction_items (
    transaction_item_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id      INT NOT NULL REFERENCES transactions(transaction_id) ON DELETE CASCADE,
    product_id          INT NOT NULL REFERENCES products(product_id)         ON DELETE RESTRICT,
    quantity            INT NOT NULL CHECK (quantity > 0),
    unit_price          NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0)
    -- line subtotal (quantity * unit_price) is DERIVED, never stored (3NF).
);
COMMENT ON TABLE transaction_items IS 'Sale line items. Resolves products<->transactions many-to-many.';


-- =============================================================================
-- 6. UTANG / CREDIT  — payments only (running-balance model)
-- =============================================================================
-- The "charges" half of the ledger is NOT duplicated here: a charge is simply a
-- transaction with payment_type='credit'. This table records money coming back
-- in. Balance = SUM(credit sales) - SUM(payments), exposed via views below.
CREATE TABLE credit_payments (
    payment_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  INT NOT NULL REFERENCES customers(customer_id) ON DELETE RESTRICT,
    amount       NUMERIC(10,2) NOT NULL CHECK (amount > 0),
    payment_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    notes        TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE credit_payments IS 'Partial/full utang repayments applied to the customer''s running balance.';


-- =============================================================================
-- 7. TRIGGERS
-- =============================================================================

-- 7a. updated_at maintenance on mutable master tables.
CREATE TRIGGER trg_products_updated_at
    BEFORE UPDATE ON products
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_customers_updated_at
    BEFORE UPDATE ON customers
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- 7b. Stock-on-hand maintenance.
--     This is the "stored column" half of the BOTH stock-tracking decision:
--     fast reads from products.stock_on_hand, with v_product_stock as the
--     strictly-derived source of truth to reconcile against.

-- Sales DECREASE stock. Handles INSERT / DELETE / UPDATE (incl. product change).
CREATE FUNCTION apply_stock_on_sale() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE products SET stock_on_hand = stock_on_hand - NEW.quantity
         WHERE product_id = NEW.product_id;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE products SET stock_on_hand = stock_on_hand + OLD.quantity
         WHERE product_id = OLD.product_id;
        RETURN OLD;
    ELSIF TG_OP = 'UPDATE' THEN
        UPDATE products SET stock_on_hand = stock_on_hand + OLD.quantity
         WHERE product_id = OLD.product_id;
        UPDATE products SET stock_on_hand = stock_on_hand - NEW.quantity
         WHERE product_id = NEW.product_id;
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Restocks INCREASE stock. Handles INSERT / DELETE / UPDATE.
CREATE FUNCTION apply_stock_on_restock() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE products SET stock_on_hand = stock_on_hand + NEW.quantity
         WHERE product_id = NEW.product_id;
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE products SET stock_on_hand = stock_on_hand - OLD.quantity
         WHERE product_id = OLD.product_id;
        RETURN OLD;
    ELSIF TG_OP = 'UPDATE' THEN
        UPDATE products SET stock_on_hand = stock_on_hand - OLD.quantity
         WHERE product_id = OLD.product_id;
        UPDATE products SET stock_on_hand = stock_on_hand + NEW.quantity
         WHERE product_id = NEW.product_id;
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_sale_stock
    AFTER INSERT OR UPDATE OR DELETE ON transaction_items
    FOR EACH ROW EXECUTE FUNCTION apply_stock_on_sale();

CREATE TRIGGER trg_restock_stock
    AFTER INSERT OR UPDATE OR DELETE ON restock_items
    FOR EACH ROW EXECUTE FUNCTION apply_stock_on_restock();


-- =============================================================================
-- 8. INDEXES  (foreign keys + frequently filtered/sorted columns)
-- =============================================================================
CREATE INDEX idx_products_category        ON products(category_id);
CREATE INDEX idx_products_unit            ON products(unit_id);

CREATE INDEX idx_restocks_supplier        ON restocks(supplier_id);
CREATE INDEX idx_restocks_date            ON restocks(restock_date);
CREATE INDEX idx_restock_items_restock    ON restock_items(restock_id);
CREATE INDEX idx_restock_items_product    ON restock_items(product_id);

CREATE INDEX idx_transactions_customer    ON transactions(customer_id);
CREATE INDEX idx_transactions_date        ON transactions(transaction_date);
CREATE INDEX idx_transactions_paytype     ON transactions(payment_type);
CREATE INDEX idx_txn_items_transaction    ON transaction_items(transaction_id);
CREATE INDEX idx_txn_items_product        ON transaction_items(product_id);

CREATE INDEX idx_credit_payments_customer ON credit_payments(customer_id);
CREATE INDEX idx_credit_payments_date     ON credit_payments(payment_date);


-- =============================================================================
-- 9. VIEWS
-- =============================================================================

-- 9a. Stock report. Side-by-side: the strictly-derived on_hand (3NF source of
--     truth) and the trigger-maintained column, so drift is instantly visible.
CREATE VIEW v_product_stock AS
SELECT
    p.product_id,
    p.name                                                   AS product,
    c.name                                                   AS category,
    u.code                                                   AS unit,
    p.reorder_level,
    COALESCE(r.qty_in,  0)                                   AS total_restocked,
    COALESCE(s.qty_out, 0)                                   AS total_sold,
    COALESCE(r.qty_in,  0) - COALESCE(s.qty_out, 0)          AS on_hand,        -- derived
    p.stock_on_hand                                          AS maintained_on_hand,  -- trigger
    (COALESCE(r.qty_in, 0) - COALESCE(s.qty_out, 0)) <= p.reorder_level
                                                            AS needs_reorder
FROM products p
JOIN categories c ON c.category_id = p.category_id
JOIN units      u ON u.unit_id     = p.unit_id
LEFT JOIN (
    SELECT product_id, SUM(quantity) AS qty_in
    FROM restock_items GROUP BY product_id
) r ON r.product_id = p.product_id
LEFT JOIN (
    SELECT product_id, SUM(quantity) AS qty_out
    FROM transaction_items GROUP BY product_id
) s ON s.product_id = p.product_id
ORDER BY p.name;
COMMENT ON VIEW v_product_stock IS 'Per-product stock: derived on_hand vs. trigger-maintained column (reconciliation).';

-- 9b. Current utang balance per customer.
--     total_utang  = SUM of credit-sale line totals
--     total_paid   = SUM of credit_payments
--     balance      = total_utang - total_paid
CREATE VIEW v_customer_balances AS
SELECT
    c.customer_id,
    c.full_name,
    c.nickname,
    c.credit_limit,
    COALESCE(ch.total_charges,  0)                           AS total_utang,
    COALESCE(pm.total_payments, 0)                           AS total_paid,
    COALESCE(ch.total_charges,  0) - COALESCE(pm.total_payments, 0) AS balance,
    c.credit_limit - (COALESCE(ch.total_charges, 0) - COALESCE(pm.total_payments, 0))
                                                            AS credit_available
FROM customers c
LEFT JOIN (
    SELECT t.customer_id, SUM(ti.quantity * ti.unit_price) AS total_charges
    FROM transactions t
    JOIN transaction_items ti ON ti.transaction_id = t.transaction_id
    WHERE t.payment_type = 'credit'
    GROUP BY t.customer_id
) ch ON ch.customer_id = c.customer_id
LEFT JOIN (
    SELECT customer_id, SUM(amount) AS total_payments
    FROM credit_payments GROUP BY customer_id
) pm ON pm.customer_id = c.customer_id
ORDER BY balance DESC;
COMMENT ON VIEW v_customer_balances IS 'Running utang balance per customer (charges - payments).';

-- 9c. The unified "utang notebook": every charge and every payment on one
--     timeline, per customer, with a running balance — exactly what a page in
--     the old handwritten ledger showed.
CREATE VIEW v_utang_ledger AS
SELECT
    customer_id,
    entry_date,
    entry_type,
    reference,
    debit,                                                   -- amount added to utang
    credit,                                                  -- amount repaid
    SUM(debit - credit) OVER (
        PARTITION BY customer_id
        ORDER BY entry_date, reference
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    )                                                       AS running_balance
FROM (
    -- Charges = credit sales
    SELECT
        t.customer_id,
        t.transaction_date                  AS entry_date,
        'charge'                            AS entry_type,
        'TXN#' || t.transaction_id          AS reference,
        SUM(ti.quantity * ti.unit_price)    AS debit,
        0::numeric                          AS credit
    FROM transactions t
    JOIN transaction_items ti ON ti.transaction_id = t.transaction_id
    WHERE t.payment_type = 'credit'
      AND t.customer_id IS NOT NULL
    GROUP BY t.customer_id, t.transaction_date, t.transaction_id

    UNION ALL

    -- Payments
    SELECT
        cp.customer_id,
        cp.payment_date                     AS entry_date,
        'payment'                           AS entry_type,
        'PAY#' || cp.payment_id             AS reference,
        0::numeric                          AS debit,
        cp.amount                           AS credit
    FROM credit_payments cp
) ledger
ORDER BY customer_id, entry_date, reference;
COMMENT ON VIEW v_utang_ledger IS 'Unified per-customer timeline of charges & payments with running balance.';

-- =============================================================================
-- 10. DATA LOADING
-- =============================================================================
-- This file is DDL-ONLY. The dataset (~676,767 rows of Filipino-brand sari-sari
-- data across six product groups) is synthesized in Python and bulk-loaded via
-- COPY -- see README.md and `python scripts/load_to_postgres.py`.
--
-- The loader temporarily disables the stock triggers during COPY for speed,
-- then sets products.stock_on_hand from first principles and re-enables them.

COMMIT;

-- =============================================================================
--  End of schema.sql  (DDL only -- data comes from the synthesis pipeline)
--  Quick checks after loading:
--    SELECT * FROM v_product_stock LIMIT 20;      -- on_hand == maintained_on_hand
--    SELECT * FROM v_customer_balances LIMIT 20;  -- per-customer utang
--    SELECT * FROM v_utang_ledger LIMIT 50;       -- running-balance timeline
-- =============================================================================
